/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAttekintesRouteImport } from './routes/_authenticated/attekintes'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedEmailSorRouteImport } from './routes/_authenticated/email-sor'
import { Route as AuthenticatedFelhasznalokRouteImport } from './routes/_authenticated/felhasznalok'
import { Route as AuthenticatedProjektekRouteImport } from './routes/_authenticated/projektek'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAttekintesRoute = AuthenticatedAttekintesRouteImport.update({
  id: '/attekintes',
  path: '/attekintes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailSorRoute = AuthenticatedEmailSorRouteImport.update({
  id: '/email-sor',
  path: '/email-sor',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFelhasznalokRoute =
  AuthenticatedFelhasznalokRouteImport.update({
    id: '/felhasznalok',
    path: '/felhasznalok',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjektekRoute = AuthenticatedProjektekRouteImport.update({
  id: '/projektek',
  path: '/projektek',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attekintes': typeof AuthenticatedAttekintesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/email-sor': typeof AuthenticatedEmailSorRoute
  '/felhasznalok': typeof AuthenticatedFelhasznalokRoute
  '/projektek': typeof AuthenticatedProjektekRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attekintes': typeof AuthenticatedAttekintesRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/email-sor': typeof AuthenticatedEmailSorRoute
  '/felhasznalok': typeof AuthenticatedFelhasznalokRoute
  '/projektek': typeof AuthenticatedProjektekRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attekintes': typeof AuthenticatedAttekintesRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/email-sor': typeof AuthenticatedEmailSorRoute
  '/_authenticated/felhasznalok': typeof AuthenticatedFelhasznalokRoute
  '/_authenticated/projektek': typeof AuthenticatedProjektekRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attekintes'
    | '/crm'
    | '/email-sor'
    | '/felhasznalok'
    | '/projektek'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attekintes'
    | '/crm'
    | '/email-sor'
    | '/felhasznalok'
    | '/projektek'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attekintes'
    | '/_authenticated/crm'
    | '/_authenticated/email-sor'
    | '/_authenticated/felhasznalok'
    | '/_authenticated/projektek'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/attekintes': {
      id: '/_authenticated/attekintes'
      path: '/attekintes'
      fullPath: '/attekintes'
      preLoaderRoute: typeof AuthenticatedAttekintesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-sor': {
      id: '/_authenticated/email-sor'
      path: '/email-sor'
      fullPath: '/email-sor'
      preLoaderRoute: typeof AuthenticatedEmailSorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/felhasznalok': {
      id: '/_authenticated/felhasznalok'
      path: '/felhasznalok'
      fullPath: '/felhasznalok'
      preLoaderRoute: typeof AuthenticatedFelhasznalokRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projektek': {
      id: '/_authenticated/projektek'
      path: '/projektek'
      fullPath: '/projektek'
      preLoaderRoute: typeof AuthenticatedProjektekRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttekintesRoute: typeof AuthenticatedAttekintesRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedEmailSorRoute: typeof AuthenticatedEmailSorRoute
  AuthenticatedFelhasznalokRoute: typeof AuthenticatedFelhasznalokRoute
  AuthenticatedProjektekRoute: typeof AuthenticatedProjektekRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttekintesRoute: AuthenticatedAttekintesRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedEmailSorRoute: AuthenticatedEmailSorRoute,
  AuthenticatedFelhasznalokRoute: AuthenticatedFelhasznalokRoute,
  AuthenticatedProjektekRoute: AuthenticatedProjektekRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
